### ISSUE TITLE
Lack of frontmatter to the microsoft botframework blog post

### ISSUE THREAD

**Issue by huan** [wechaty/bot5.club#38]
@andrewdyhhub

Please read <https://www.bot5.club/manuals/blog/> and see others posts for an example.

The following information is required for a blog post:

```yaml
---
title: 这里是 Blog 的标题
author: ${your_github_username}
categories: events
tags:
  - tag1
  - tag2
---
```
